feat(snap): Add startup configure options and update versioning logic
edgexfoundry/device-modbus-go pull request #198
Opened 2020-12-09 18:00 UTC by siggiskulason

1) Add two new configure options:

- To change the default startup duration use:
sudo snap set edgex-device-modbus startup-duration=n

- To change the default startup interval use:
sudo snap set edgex-device-modbus startup-interval=n

2) Update the way version numbers are
generated when building the snap:

- Remove git tag and datestamp from the version number.
    ('1.1.3-dev.5' vs '1.1.3-dev.4-20201021+856f4f8')
- Use 'snapcraftctl set-version' instead of deprecated 'version-script'

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

1) The module go-mod-bootstrap implements a service dependency check on startup which ensures that all of the runtime dependencies of a particular service are met before the service transitions to active state. The logic implements a basic retry loop with a maximum duration and sleep interval. If the dependent services are not available, the service sleeps for the defined interval (default: 1s) and then tries again up to a maximum duration (default: 60s). These values can be overridden via environment variables.

2) The snap version is in the format "1.1.3-dev.4-20201021+856f4f8"

Issue Number:
N/A

## What is the new behavior?

1) This PR covers updating  the device service snap to allow these variables to be set/queried via the configure hook:

- To change the default startup duration use:
sudo snap set edgex-device-modbus startup-duration=n

- To change the default startup interval use:
sudo snap set edgex-device-modbus startup-interval=n

2) The snap version will be in the format "1.1.3-dev.4"

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
N/A

## Are there any specific instructions or things that should be known prior to reviewing?
N/A

## Other information
N/A

2020-12-09 23:36 UTC, tonyespy requested changes
Looks good. I verified that the settings are accepted and that the service properly logs the config overrides.

That said, would you mind breaking the changes into two commits, one for the config hook changes, and one for the version changes?

2020-12-10 13:14 UTC, siggiskulason commented
> Looks good. I verified that the settings are accepted and that the service properly logs the config overrides.
> 
> That said, would you mind breaking the changes into two commits, one for the config hook changes, and one for the version changes?

@tonyespy - Thanks, done. The changes are now in two commits.

2020-12-10 15:32 UTC, tonyespy approved these changes
LGTM

2020-12-10 15:40 UTC, lenny-intel approved these changes
LGTM

2020-12-10 15:40 UTC, merged