fix (device services): Remove write of input types
edgexfoundry/device-modbus-go pull request #208
Opened 2020-12-23 14:00 UTC by vijay-hcl-epl

fixes: #180; Removed input types from the SetValue function

Signed-off-by: Vijay Annamalaisamy <vijayone1708@gmail.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

DISCRETES_INPUT and INPUT_REGISTERS are read only registers but are allowed to be writable in the SetValue function

Issue Number: 180

## What is the new behavior?
DISCRETES_INPUT and INPUT_REGISTERS were removed from the SetValue function and writing to these registers can never happen.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
No

## Are there any specific instructions or things that should be known prior to reviewing?
No

## Other information
None

2020-12-23 15:11 UTC, cloudxxx8 requested changes
Instead of removing the case, may we return the error to state this is read only?

2020-12-23 15:31 UTC, vijay-hcl-epl commented
> Instead of removing the case, may we return the error to state this is read only?

Sure @cloudxxx8. That makes more sense. I will make the change and submit

2020-12-25 08:39 UTC, vijay-hcl-epl commented
@cloudxxx8 I have made changes and submitted again as suggested. Could you please review and let me know?

2021-01-02 01:57 UTC, cloudxxx8 approved these changes
LGTM

2021-01-02 01:57 UTC, merged