feat: supply string type
edgexfoundry/device-modbus-go pull request #262
Opened 2021-06-14 13:31 UTC by hongda3141

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/master/.github/Contributing.md

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions

## Other information

2021-06-14 13:33 UTC, hongda3141 commented
change log:
1. modify  variable "stringLength" to "wordLength"
2. change bit length of string from 1 to 16
3. change swith-case to if-else block

2021-06-14 13:50 UTC, hongda3141 commented
@weichou1229 
PTAL again ，thanks

2021-06-15 05:03 UTC, cloudxxx8 requested changes
We changed the DeviceProfile data model.
Please modify the sample profile.  Here is the example:
https://github.com/edgexfoundry/device-modbus-go/blob/b09d9ba1a72cafb6b38617a4d5eb8b9f0ac4b1bc/cmd/res/profiles/modbus.test.device.profile.yml

2021-06-15 06:08 UTC, weichou1229 requested changes

2021-06-15 06:08 UTC, weichou1229 commented on internal/driver/deviceclient.go
> +			length = 1
Please return error if the Attribute is invalid.

2021-06-15 06:08 UTC, weichou1229 commented on internal/driver/deviceclient.go
> +	}
Please move those code snippet to https://github.com/edgexfoundry/device-modbus-go/blob/700bb1d367cb9371150de4b976218c3919e9a955/internal/driver/deviceclient.go#L260

2021-06-15 06:14 UTC, weichou1229 requested changes

2021-06-15 06:14 UTC, weichou1229 commented on internal/driver/deviceclient.go
> +	} else {
Please move those code snippet to https://github.com/edgexfoundry/device-modbus-go/blob/700bb1d367cb9371150de4b976218c3919e9a955/internal/driver/deviceclient.go#L260

2021-06-15 06:15 UTC, weichou1229 requested changes

2021-06-15 06:15 UTC, weichou1229 commented on internal/driver/deviceclient.go
> +	} else {
Please move those code snippet to https://github.com/edgexfoundry/device-modbus-go/blob/700bb1d367cb9371150de4b976218c3919e9a955/internal/driver/deviceclient.go#L260

2021-06-15 06:33 UTC, weichou1229 requested changes

2021-06-15 06:33 UTC, weichou1229 commented on internal/driver/constant.go
> +	WORD_LENGTH            = "wordLength"
Rename the `wordLength` to `stringRegisterSize` and check the register size should be within the range of 1~123.

The register size limit can refer to https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf
> 6.12 16 (0x10) Write Multiple registers
This function code is used to write a block of contiguous registers (1 to 123 registers) in a
remote device.

2021-06-15 10:43 UTC, hongda3141 commented
@weichou1229
PTAL again ，thanks a lot for the advice

2021-06-16 02:39 UTC, weichou1229 requested changes
No problem.
Since we change the data model in V2, please verify the GET and PUT command works with edgex-go master branch.

2021-06-16 02:39 UTC, weichou1229 commented on cmd/res/devices/modbus.test.devices.toml
> +        Resource = 'ReadString'
This pre-defined device is invalid. 
The valid format should be: 
```
[[DeviceList]]
  Name = 'Modbus-TCP-Read-String'
  ProfileName = 'Test.Device.Modbus.String.Profile'
  Description = 'use for auto read a string value'
  labels = [ 'modbus TCP' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-tcp]
        Address = '0.0.0.0'
        Port = '1502'
        UnitID = '1'
        Timeout = '5'
        IdleTimeout = '5'
  [[DeviceList.AutoEvents]]
        Interval = '20s'
        OnChange = false
        SourceName = 'ReadString'
```

2021-06-16 02:39 UTC, weichou1229 commented on cmd/res/profiles/modbus.test.device.string.profile.yml
> +      { primaryTable: "INPUT_REGISTERS", startingAddress: "1", stringRegisterSize: "1"}
The startingAddress and stringRegisterSize should be integer. Please change to `{ primaryTable: "INPUT_REGISTERS", startingAddress: 1, stringRegisterSize: 1}`

2021-06-16 02:39 UTC, weichou1229 commented on cmd/res/profiles/modbus.test.device.string.profile.yml
> +      { primaryTable: "HOLDING_REGISTERS", startingAddress: "15", stringRegisterSize: "5"}
The startingAddress and stringRegisterSize should be integer. Please change to `{ primaryTable: "INPUT_REGISTERS", startingAddress: 1, stringRegisterSize: 1}`

2021-06-16 07:03 UTC, hongda3141 commented
@weichou1229
that`s right, profiles should update to v2 too,
PTAL again ，thanks

2021-06-16 09:28 UTC, weichou1229 commented
@hongda3141 
The Get and Put command works incorrectly.

1. For the Get command, I thought the value should be decoded to a readable string.
`"value" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"`
```
% curl http://localhost:59882/api/v2/device/name/Modbus-TCP-Read-String/StringB | json_pp
{
   "apiVersion" : "v2",
   "event" : {
      "apiVersion" : "v2",
      "deviceName" : "Modbus-TCP-Read-String",
      "id" : "669f5d9f-2004-47ad-9533-e15ff452304d",
      "origin" : 1623834796385661000,
      "profileName" : "Test.Device.Modbus.String.Profile",
      "readings" : [
         {
            "binaryValue" : null,
            "deviceName" : "Modbus-TCP-Read-String",
            "id" : "3fb25504-d6da-4525-8143-3a55f84299ad",
            "mediaType" : "",
            "origin" : 1623834796385624000,
            "profileName" : "Test.Device.Modbus.String.Profile",
            "resourceName" : "StringB",
            "value" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
            "valueType" : "String"
         }
      ],
      "sourceName" : "StringB"
   },
   "statusCode" : 200
}
```

2. For the Put command, I got the transform error.
```
% curl http://localhost:59882/api/v2/device/name/Modbus-TCP-Read-String/StringB -X PUT -H "Content-Type: application/json" -d '{
    "StringB":"test-string"
  }' | json_pp
{
   "apiVersion" : "v2",
   "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"error writing DeviceResourece StringB for Modbus-TCP-Read-String -\\u003e transform command value failed, err: failed to transform test-string to []byte\",\"statusCode\":500}",
   "statusCode" : 500
}

```

2021-06-21 15:00 UTC, hongda3141 commented
> @hongda3141
> The Get and Put command works incorrectly.
> 
> 1. For the Get command, I thought the value should decode to a readable string.
>    `"value" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"`
> 
> ```
> % curl http://localhost:59882/api/v2/device/name/Modbus-TCP-Read-String/StringB | json_pp
> {
>    "apiVersion" : "v2",
>    "event" : {
>       "apiVersion" : "v2",
>       "deviceName" : "Modbus-TCP-Read-String",
>       "id" : "669f5d9f-2004-47ad-9533-e15ff452304d",
>       "origin" : 1623834796385661000,
>       "profileName" : "Test.Device.Modbus.String.Profile",
>       "readings" : [
>          {
>             "binaryValue" : null,
>             "deviceName" : "Modbus-TCP-Read-String",
>             "id" : "3fb25504-d6da-4525-8143-3a55f84299ad",
>             "mediaType" : "",
>             "origin" : 1623834796385624000,
>             "profileName" : "Test.Device.Modbus.String.Profile",
>             "resourceName" : "StringB",
>             "value" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
>             "valueType" : "String"
>          }
>       ],
>       "sourceName" : "StringB"
>    },
>    "statusCode" : 200
> }
> ```
> 
> 1. For the Put command, I got the transform error.
> 
> ```
> % curl http://localhost:59882/api/v2/device/name/Modbus-TCP-Read-String/StringB -X PUT -H "Content-Type: application/json" -d '{
>     "StringB":"test-string"
>   }' | json_pp
> {
>    "apiVersion" : "v2",
>    "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"error writing DeviceResourece StringB for Modbus-TCP-Read-String -\\u003e transform command value failed, err: failed to transform test-string to []byte\",\"statusCode\":500}",
>    "statusCode" : 500
> }
> ```

thanks very much，i`ll fix that

2021-06-22 04:35 UTC, hongda3141 commented
> No problem.
> Since we change the data model in V2, please verify the GET and PUT command works with edgex-go master branch.

@weichou1229  hi，i found there is no edgex-lanch.sh in branch master, could you tell me which branch did you used for edgex-go? i always used and tested in fuji, but i think maybe it is too old for v2 version.

2021-06-22 07:12 UTC, weichou1229 commented
@hongda3141 

> i found there is no edgex-lanch.sh in branch master

It was removed in master branch

>  could you tell me which branch did you used for edgex-go?

master branch


You can use the following script before community add it back.
```
#!/bin/bash

DIR=$PWD
CMD=../cmd

# Kill all edgex-* stuff
function cleanup {
	pkill edgex
}

# disable secret-store integration
export EDGEX_SECURITY_SECRET_STORE=false

###
# Core Command
###
cd $CMD/core-command
# Add `edgex-` prefix on start, so we can find the process family
exec -a edgex-core-command ./core-command &
cd $DIR

###
# Core Data
###
cd $CMD/core-data
exec -a edgex-core-data ./core-data &
cd $DIR

###
# Core Metadata
###
cd $CMD/core-metadata
exec -a edgex-core-metadata ./core-metadata &
cd $DIR

trap cleanup EXIT

while : ; do sleep 1 ; done
```

2021-06-22 10:17 UTC, hongda3141 commented
thanks a lot

2021-06-25 06:26 UTC, hongda3141 commented
@weichou1229
i fixed the PUT and GET command error, 
PTAL thanks

2021-06-28 02:12 UTC, weichou1229 requested changes

2021-06-28 02:12 UTC, weichou1229 commented on internal/driver/deviceclient.go
> +		res = trimString(dataBytes)
I thought you can trim the zero value by something like `bytes.Trim(dataBytes, string(rune(0)))` instead of writing another function

2021-06-28 02:12 UTC, weichou1229 commented on cmd/res/devices/modbus.test.devices.toml
> +  ProfileName = 'Test.Device.Modbus.String.Profile'
Change the profile name to `Test-Device-Modbus-String-Profile`

2021-06-28 06:28 UTC, hongda3141 commented on internal/driver/deviceclient.go
> +		res = trimString(dataBytes)
yeah , that is more concise than writing another function

2021-06-28 06:33 UTC, hongda3141 commented
@weichou1229
i update the codes with using build-in method for trimming the zero value, 
PTAL thanks

2021-06-29 01:13 UTC, weichou1229 approved these changes
LGTM

2021-06-29 01:57 UTC, cloudxxx8 commented
hold until 2.0.0 release
this is targeting to 2.0.1

2021-08-03 09:04 UTC, cloudxxx8 approved these changes
LGTM

2021-08-03 09:05 UTC, merged